# Generated by Django 6.0.2 on 2026-02-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(default='Python, Django', max_length=200),
            preserve_default=False,
        ),
    ]
